/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaviajes.presentacion;

import agenciaviajes.negocio.Cliente;
import agenciaviajes.negocio.GestorClientes;
import agenciaviajes.utils.Utilidades;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author Alexander
 */
public class GUIClientesPorSexo extends javax.swing.JFrame implements AView {

    int TotalClientes = 0;
    int TotalHombres = 0;
    int TotalMujeres = 0;
    float PorcentajeHombres = 0;
    float PorcentajeMujeres = 0;
    
    
    /**
     * Creates new form GUIClientesPorSexo
     */
    public GUIClientesPorSexo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Porcentaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClientesPorSexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIClientesPorSexo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private void llenarTabla(ArrayList<Cliente> clientes) {
        //this.inicializarTabla();
        //DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();

        Object rowData[] = new Object[7];
        for (Cliente cli : clientes) {
            rowData[0] = cli.getId();
            rowData[1] = cli.getNombres();
            rowData[2] = cli.getApellidos();
            rowData[3] = cli.getDireccion();
            rowData[4] = cli.getCelular();
            rowData[5] = cli.getEmail();
            rowData[6] = cli.getSexo();
            //model.addRow(rowData);
        }
    }

    @Override
    public void actualizar(AModel amodel){
        try{
            GestorClientes gestor = (GestorClientes) amodel;
            gestor.consultarClientes();
            this.actualizarDatos(gestor);
            repaint();
                           
        }catch(Exception e){
            
        }
    }
    
    public void actualizarDatos(GestorClientes gestor){
        try{
        this.TotalHombres = gestor.numeroHombres();
        this.TotalMujeres = gestor.numeroMujeres();
        this.TotalClientes = this.TotalHombres+this.TotalMujeres;
        
        this.PorcentajeHombres = this.TotalHombres*100/this.TotalClientes;
        this.PorcentajeMujeres = this.TotalMujeres*100/this.TotalClientes;
    
        }catch(Exception e){
            
        }
    }
    
    public int mayorValor(int pHombres,int pMujeres){
        if(pHombres>pMujeres){
            return pHombres;
        }else{
            return pMujeres;
        }
    }
    
    public void paint(Graphics g){
        super.paint(g);
        int valorMayor = mayorValor(this.TotalHombres,this.TotalMujeres);
        int largoHombres = this.TotalHombres*300/this.TotalClientes;
        int largoMujeres = this.TotalMujeres*300/this.TotalClientes;
        
        g.setColor(new Color(255,0,0));
        g.fillRect(100, 100, largoHombres, 40);
        g.setColor(Color.BLACK);
        g.drawString("Hombres", 10, 125);
        g.drawString(Float.toString(this.PorcentajeHombres), 410, 130);
        g.drawRect(100,100, 300, 40);
        
        g.setColor(new Color(255,0,0));
        g.fillRect(100, 150, largoMujeres, 40);
        g.setColor(Color.BLACK);
        g.drawString("Mujeres", 10, 175);
        g.drawString(Float.toString(this.PorcentajeMujeres), 410, 170);
        g.drawRect(100,150, 300, 40);
        
        
    }
    
    
    
    
    
    
    public void actualizar2(AModel amodel) {
        try {
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.consultarClientes();
            llenarTabla(listado);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIClientesVer.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al consultar clientes", "Atención");
        }
    }

}
